### ISSUE TITLE
Not an issue but a question 

### ISSUE THREAD

**Issue by K1udg3** [guanquann/Stocksera-API#1]
Is there a way to pull the historical max pain? 
I'm aware it changes based on OI so that makes it more complicated but is the data there ? Like what was the max pain of a stock a week before expiration or a month before expiration. 

PS I love your work sir.

**Comment by guanquann** [comment]
Hi there, sorry for the late reply. Currently there is no historical data for max pain. However, I might consider adding it for popular stocks in the future!
